name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Install deps
      run: go mod tidy

    - name: Run golangci-lint
      uses:  golangci/golangci-lint-action@v8.0.0
      with:
            version: latest
            
    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build -o gocli main.go
